### PR TITLE
login with validation, console logs on submit

### LINKED ISSUE #67: Frontend page for login

### PR DESCRIPTION
**Pull request by seagulley**
Added a login page with email and password validation. It prints out the email and password on submit, and only if they are both valid.

### CODE REVIEW

**Review by Sooraj-beep — APPROVED** [review]

**Comment by dimassudjito** [comment]
@Sooraj-beep Are we planning to merge PR to develop or main?

**Comment by Sooraj-beep** [comment]
@dimassudjito @seagulley first to develop then to main

**Comment by dimassudjito** [comment]
> @dimassudjito @seagulley first to develop then to main

I see, we should be more careful about the branch target of the PR next time

**Comment by seagulley** [comment]
Okay sorry I’m figuring out how to add stuff for login routing right now

**Pull request merged**
